name: .NET

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Continuous Deployment

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Run tests and collect coverage
      run: |
        dotnet test --no-build --collect:"XPlat Code Coverage" --results-directory ./TestResults

    - name: Check code coverage
      run: |
        COVERAGE=$(dotnet reportgenerator "-reports:./TestResults/*/coverage.cobertura.xml" "-reporttypes:Summary")
        echo "Code coverage: $COVERAGE"
        # Extra validation step for 80% coverage
        if [[ "$COVERAGE" != *"80%"* ]]; then
          echo "Code coverage is below 80%. Merge blocked."
          exit 1
        fi
