name: .NET

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Continuous Deployment

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Install ReportGenerator Tool
      run: |
        dotnet tool install --global dotnet-reportgenerator-globaltool --version 5.4.4
        export PATH="$PATH:/root/.dotnet/tools"  # Garantir que o caminho seja atualizado

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Run tests and collect coverage
      run: |
        dotnet test --no-build --collect:"XPlat Code Coverage" --results-directory ./TestResults

    - name: Check code coverage
      run: |
        # Gerar o relatório de cobertura com a ferramenta ReportGenerator
        reportgenerator "-reports:./TestResults/*/coverage.cobertura.xml" "-reporttypes:Summary"
        
        # Extra validation step for 80% coverage
        COVERAGE=$(reportgenerator "-reports:./TestResults/*/coverage.cobertura.xml" "-reporttypes:Summary" | grep -oP '(?<=Line coverage: )[^%]*')
        echo "Code coverage: $COVERAGE%"
        if (( $(echo "$COVERAGE < 80" | bc -l) )); then
          echo "Code coverage is below 80%. Merge blocked."
          exit 1
        fi
