name: .NET

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Continuous Deployment

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test with coverage
      run: |
        dotnet test --no-build --collect:"XPlat Code Coverage" --results-directory ./TestResults
    - name: Check Code Coverage
      run: |
        # Usa xmllint para extrair a cobertura de código diretamente do XML
        coverage=$(xmllint --xpath "string(//coverage/@linescovered)" ./TestResults/coverage.cobertura.xml)
        total_lines=$(xmllint --xpath "string(//coverage/@lines)" ./TestResults/coverage.cobertura.xml)
        
        # Calcula a cobertura percentual
        percentage=$(echo "scale=2; ($coverage / $total_lines) * 100" | bc)
        
        # Define a cobertura mínima (80%)
        min_coverage=80
        
        # Exibe a cobertura calculada
        echo "Coverage: $percentage%"
        
        # Verifica se a cobertura é inferior a 80%
        if (( $(echo "$percentage < $min_coverage" | bc -l) )); then
          echo "Code coverage is below the minimum threshold of $min_coverage%. Current coverage is $percentage%"
          exit 1
        fi
