name: .NET

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Continuous Deployment

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Run Tests and Collect Coverage
      run: |
        dotnet test --collect:"XPlat Code Coverage"

    - name: Generate Coverage Report
      run: |
        dotnet reportgenerator -reports:./TestResults/**/coverage.cobertura.xml -targetdir:./TestResults/CoverageReport -reporttypes:Html

    - name: Check Coverage
      run: |
        coverage=$(grep -oP '(?<=<coverage line-rate=")[^"]*' ./TestResults/coverage.cobertura.xml)
        if (( $(echo "$coverage < 0.8" | bc -l) )); then
          echo "Code coverage is below 80%: $coverage"
          exit 1
        else
          echo "Code coverage is acceptable: $coverage"
        fi
